plugins {
    id "java"
    id "org.jetbrains.kotlin.jvm" version "2.2.10"
}

group "tictactoe4k"
version "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation platform("org.http4k:http4k-bom:6.15.1.0")
    implementation "org.http4k:http4k-core"
    implementation "org.http4k:http4k-server-apache"
    implementation "org.http4k:http4k-client-okhttp"
    implementation "org.http4k:http4k-format-jackson"
    implementation "org.http4k:http4k-testing-approval"
    implementation "org.http4k:http4k-template-handlebars"
    implementation "org.jetbrains.kotlin:kotlin-reflect"
    implementation "org.slf4j:slf4j-nop:2.0.17" // Suppress log warnings from handlebars
	implementation "dev.forkhandles:result4k:2.22.4.0"
    implementation "io.arrow-kt:arrow-core:2.1.2"
    testImplementation "io.strikt:strikt-core:0.35.1"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit5"
    testImplementation "org.junit.jupiter:junit-jupiter:5.13.4"
}

kotlin.sourceSets {
    main.kotlin.srcDirs += "src/main"
    test.kotlin.srcDirs += "src/test"
}

kotlin {
    jvmToolchain(21)
}

tasks.test {
    useJUnitPlatform()
}