plugins {
    id "java"
    id "org.jetbrains.kotlin.jvm" version "2.2.20"
}

group "tictactoe4k"
version "1.0-SNAPSHOT"

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation platform("org.http4k:http4k-bom:6.18.0.1")
    implementation "org.http4k:http4k-core"
    implementation "org.http4k:http4k-server-jetty11"
    implementation "org.http4k:http4k-testing-approval"
    implementation "org.http4k:http4k-template-handlebars"
    implementation "org.jetbrains.kotlin:kotlin-reflect"
    implementation "org.slf4j:slf4j-nop:2.0.17" // Suppress log warnings from handlebars
    implementation "com.h2database:h2:2.3.232"
	implementation "dev.forkhandles:result4k:2.22.5.0"
    testImplementation "io.strikt:strikt-core:0.35.1"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit5"
    testImplementation "org.junit.jupiter:junit-jupiter:5.13.4"
}

kotlin.sourceSets {
    main.kotlin.srcDirs += "src/main"
    test.kotlin.srcDirs += "src/test"
}

// https://github.com/Kotlin/KEEP/blob/main/proposals/KEEP-0412-unused-return-value-checker.md
//kotlin.compilerOptions.freeCompilerArgs.add("-Xreturn-value-checker=full")

kotlin {
    jvmToolchain(21)
}

tasks.test {
    useJUnitPlatform()
}